\connect DB_NAME;

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS tbank_cleaned (
    TRANSACTIONID      BIGINT PRIMARY KEY,
    ACCOUNTFROM        BIGINT NOT NULL,
    ACCOUNTTO          BIGINT NOT NULL,
    BANKIDFROM        BIGINT NOT NULL,
    BANKIDTO          BIGINT NOT NULL,
    TRANSACTIONAMOUNT  DECIMAL(18, 6) NOT NULL,
    EXCHANGERATE       DECIMAL(18, 6) NOT NULL,
    TRANSACTIONDATE    TIMESTAMP NOT NULL,
    TRANSACTIONTYPE    INTEGER NOT NULL,
    INTERIMBALANCE     DECIMAL(18, 2) NOT NULL,
    ACCOUNTTO_INTERIMBALANCE DECIMAL(18, 2) NOT NULL,
    CURRENCY            VARCHAR(50) NOT NULL,
    QUOTECURRENCY      VARCHAR(50) NOT NULL,
    PAYMENTMODE        VARCHAR(50) NOT NULL,
    OVERRIDEFLAG       BOOLEAN NOT NULL,
    NARRATIVE           TEXT
);

CREATE TABLE tbank_users_cleaned (
    CUSTOMERID                BIGINT PRIMARY KEY,
    FAMILYNAME                VARCHAR(255) NOT NULL,
    GIVENNAME                 VARCHAR(255) NOT NULL,
    DATEOFBIRTH              DATE NOT NULL,
    CITY                       VARCHAR(255),
    COUNTRY                    VARCHAR(255) NOT NULL,
    POSTALCODE                VARCHAR(20),
    CELLCOUNTRYCODE          VARCHAR(20) NOT NULL,
    PHONECOUNTRYCODE         VARCHAR(20) NOT NULL,
    CERTIFICATEEXPIRYDATE    DATE NOT NULL,
    CERTIFICATEISSUER         VARCHAR(255) NOT NULL,
    CERTIFICATETYPE           VARCHAR(255) NOT NULL,
    LASTMAINTENANCETELLERID VARCHAR(255),
    REGISTRATIONDATE          DATE NOT NULL,
    CUSTOMERTYPE              VARCHAR(50) NOT NULL,
    NATIONALITY                VARCHAR(255) NOT NULL,
    GENDER                     VARCHAR(50),
    ETHNICGROUP               VARCHAR(255),
    OCCUPATION                 VARCHAR(255),
    EMAIL                      VARCHAR(255),
    ISBILLINGORG             BOOLEAN NOT NULL,
    ISMERCHANT                BOOLEAN NOT NULL
);
