\connect DB_NAME;

CREATE ROLE DB_USER WITH PASSWORD 'DB_PASS';
ALTER ROLE DB_USER WITH LOGIN REPLICATION;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE tbank_cleaned TO DB_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE tbank_users_cleaned TO DB_USER;