\connect DB_NAME;

CREATE ROLE DB_USER WITH PASSWORD 'DB_PASS';
ALTER ROLE DB_USER WITH LOGIN REPLICATION;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE users TO DB_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE roles TO DB_USER;
-- ALTER TABLE roles OWNER TO DB_USER;

GRANT CONNECT ON DATABASE DB_NAME TO DB_USER;
