global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: ''
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'default-team'  # Default receiver

  routes:
    - match:
        service: kafka-broker
      receiver: 'kafka-team'
    - match:
        service: postgresql
      receiver: 'database-team'

receivers:
  - name: 'default-team'
    email_configs:
      - to: ''
        send_resolved: true

  - name: 'kafka-team'
    email_configs:
      - to: 'weiting.lee.2022@scis.smu.edu.sg'
        send_resolved: true

  - name: 'database-team'
    email_configs:
      - to: 'clwt@outlook.sg'
        send_resolved: true